bool wait
bool publish_debug_image
float64 approach_offset_m
bool close_gripper
bool activate_gripper
int32 gripper_index
int32 gripper_position
int32 gripper_velocity
int32 gripper_force
int32 gripper_max_time_ms
bool gripper_wait
---
bool success
int32 error_code
string message
float64[6] target_tcp_xyz_m_rpy_rad
float64[3] object_point_camera_m
float64[3] object_point_base_m
float64 depth_m
string debug_summary
