# Orbbec color/depth stream configuration for perception.
camera_name: camera
depth_registration: true
align_mode: HW

enable_color: true
color_width: 640
color_height: 480
color_fps: 30
color_format: MJPG
color_qos: default
color_camera_info_qos: default

enable_depth: true
depth_width: 640
depth_height: 480
depth_fps: 30
depth_format: Y16
depth_qos: default
depth_camera_info_qos: default

enable_left_ir: false
enable_right_ir: false
enable_accel: false
enable_gyro: false
enable_sync_output_accel_gyro: false

enable_point_cloud: true
enable_colored_point_cloud: false
enable_d2c_viewer: false
ordered_pc: true
publish_tf: true
tf_publish_rate: 0.0
enable_frame_sync: true
enable_depth_scale: true
frame_aggregate_mode: ANY
